### ISSUE TITLE
dial tcp 127.0.0.1:22223: connectex: Connection refused

### ISSUE THREAD

**Issue by pidongqianqian** [duo/matrix-wechat#1]
项目不错。感谢！

准备搭出来自己用用，不过我使用时遇到了一些问题。日志如下：
```
matrix_wechat_agent_1  | time="2022-09-30T01:20:30+08:00" level=info msg="No more files."
matrix_wechat_agent_1  | [I] <MMKV.cpp:156::initialize> version v1.2.7 page size:4096
matrix_wechat_agent_1  | [I] <MMKV.cpp:198::initializeMMKV> root dir: C:\users\user\Application Data\Tencent\WeChat\XPlugin\Info\
matrix-wechat          | [Sep 30, 2022 01:20:40] [User/@pidong3:***.***.**/WARN] Error connecting to Wechat: : Post "http://127.0.0.1:22223/api/?type=9": dial tcp 127.0.0.1:22223: connectex: Connection refused.
matrix-wechat          | [Sep 30, 2022 01:20:40] [User/@pidong3:***.***.**/ERROR] Failed to log in:%!(EXTRA *wechat.ErrorResponse=: Post "http://127.0.0.1:22223/api/?type=9": dial tcp 127.0.0.1:22223: connectex: Connection refused.)
```

附图web客户端图
![image](https://user-images.githubusercontent.com/20850873/193100946-9b0524b5-ef8a-49b2-9658-4be3d580475a.png)

目前使用的是基于 docker 的 matrix-wechat-agent, 
希望能给一些思路。

**Comment by duo** [comment]
Docker那边的配置是怎么样的? 这个是 docker 里的微信没启动起来

**Comment by pidongqianqian** [comment]
```
  matrix-wechat:
      image: lxduo/matrix-wechat:latest
      restart: unless-stopped
      ports:
        - "39320:39320"
      container_name: matrix-wechat
      volumes:
        - /home/matrix/bridges/matrix-wechat:/data
      depends_on:
        - matrix-postgres
        - matrix-homeserver
      networks:
        - matrix-bridge
  
  matrix_wechat_agent:
    hostname: matrix-wechat-agent
    image: lxduo/matrix-wechat-docker:latest
    restart: unless-stopped
    depends_on:
      - matrix-wechat
    environment:
      TZ: Asia/Shanghai
      WECHAT_HOST: ws://matrix-wechat:20002
      WECHAT_SECRET: *******
    #shm_size: "1gb"
    #devices:
    #  - /dev/dri:/dev/dri
    #ports:
    #  - 15905:5905
    volumes:
      - ./matrix-wechat-agent:/home/user/matrix-wechat-agent
    networks:
      - matrix-bridge
 
  matrix-nginx:
    image: nodefy/nginx:v1.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/matrix/nginx:/etc/nginx/conf.d
      - /home/matrix/matrix-web:/usr/share/nginx/html
      - /home/matrix/homeserver/certs:/certs
    container_name: matrix-nginx
    depends_on:
      - matrix-homeserver
        #- matrix-slack
    networks:
      - matrix-bridge

```
因为我这个里面部署了很多其他的bridge，所以并不是和 安装步骤的配置 完全一致，不一样的地方主要有 容器名称和网络名称部分，服务自己的端口，使用的是nginx 代理
