### ISSUE TITLE
Matrix-Wechat 可以发送消息到微信但是无法收到微信的消息，似乎是房间创建失败

### ISSUE THREAD

**Issue by xr1s** [duo/matrix-wechat#34]
在尝试用 matrix-wechat 桥接到 beeper 的 matrix 服务上。启动成功了，配置大体上应该是正确的，能发消息但是无法收消息（后附修改过的字段）。

具体来说，目前的状况是能使用 matrix 客户端通过 matrix-wechat 发送消息（手机微信上能收到 matrix 客户端发送的消息）。但是 matix 客户端不会展示微信上收到的消息。每次微信收到消息，matrix-wechat 都会有如下报错：

![photo_2024-11-18_21-09-24](https://github.com/user-attachments/assets/6965f4a4-85b7-4a6e-b8ea-4d2504f10919)

跟踪了一下错误链路，是在 mautrix/go 中扔出来的。我不熟悉 matrix 协议的细节，想请教一下这可能是什么原因导致的。

配置文件：

```yaml
# bbctl 的 registration.yaml
id: "00000000-0000-0000-0000-000000000000"
url: "http://localhost:17778"
as_token: "hua_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_XXXXXX"
hs_token: "huh_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_XXXXXX"
sender_localpart: sh-wechatbot
rate_limited: false
namespaces:
    users:
        - regex: '@sh-wechat_.+:beeper\.local'
          exclusive: true
```

```yaml
# matrix-wechat 的 config.yaml
homeserver:
    address: https://matrix.beeper.com/_hungryserv/example
    domain: beeper.local
    software: hungry
appservice:
    database:
        type: sqlite3-fk-wal
        uri: "file:matrix-wechat.data?_txlock=immediate"
    id: "00000000-0000-0000-0000-000000000000"
    bot:
        username: sh-wechatbot
    as_token: "hua_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_XXXXXX"
    hs_token: "huh_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_XXXXXX"
bridge:
    hs_proxy: ""
    permissions:
        "@example:beeper.com": admin
    encryption:
        allow: true
        appservice: true
```
